language: python
dist: xenial

services:
  - memcached
  - redis

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - if [[ `python --version | grep 3.6` ]]; then pip install -U setuptools; fi;
  - pip install .
  - pip install -r requirements.txt

script:
  - flake8 esipy
  - flake8 test
  - coverage run setup.py test

after_success: coveralls
